POWERUP_CONFIG = {
    "health": {
        "img"            : "assets/images/icon/health.png",
        "size"           : (70, 70),
        "heal_percentage": 0.25,
        "drop_chance"    : 0.15,
        "fall_speed"     : 2,
        "duration"       : 8000,
        "points"         : 50,
    },
    "repair": {
        "img"            : "assets/images/icon/repair.png",
        "size"           : (70, 70),
        "heal_percentage": 0.15,
        "drop_chance"    : 0.10,
        "fall_speed"     : 2,
        "duration"       : 8000,
        "points"         : 25,
    },
    "shield": {
        "img"        : "assets/images/icon/shield.png",
        "size"       : (70, 70),
        "drop_chance": 0.08,
        "fall_speed" : 2,
        "duration"   : 8000,
        "points"     : 75,
    },
    "double_laser": {
        "img"            : "assets/images/icon/doubleLaser.png",
        "size"           : (70, 70),
        "drop_chance"    : 0.05,
        "fall_speed"     : 2,
        "duration"       : 10000,
        "points"         : 100,
        "weapon_duration": 15000,
    },
    "speed_boost": {
        "img"             : "assets/images/icon/speedup.png",
        "size"            : (70, 70),
        "drop_chance"     : 0.06,
        "fall_speed"      : 2,
        "duration"        : 8000,
        "points"          : 75,
        "speed_duration"  : 10000,
        "speed_multiplier": 1.75,
    },
    "emp": {
        "img"        : "assets/images/icon/nuke.png",
        "size"       : (70, 70),
        "drop_chance": 0.05,
        "fall_speed" : 2,
        "duration"   : 10000,
        "points"     : 150,
        "min_stage"  : 1,
    }
}
